#pragma checksum "C:\Users\cauag\Documents\SENAC\Modulo 1\Projeto Integrador\Views\Jogos\Index.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "9f5f431603515e69b3de80b3f4b76efe8d5ed7ecfbaa3426430007af045c3fa0"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Jogos_Index), @"mvc.1.0.view", @"/Views/Jogos/Index.cshtml")]
namespace AspNetCore
{
    #line hidden
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Mvc;
    using global::Microsoft.AspNetCore.Mvc.Rendering;
    using global::Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "C:\Users\cauag\Documents\SENAC\Modulo 1\Projeto Integrador\Views\_ViewImports.cshtml"
using Projeto_Integrador;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "C:\Users\cauag\Documents\SENAC\Modulo 1\Projeto Integrador\Views\_ViewImports.cshtml"
using Projeto_Integrador.Models;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA256", @"9f5f431603515e69b3de80b3f4b76efe8d5ed7ecfbaa3426430007af045c3fa0", @"/Views/Jogos/Index.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA256", @"e099c02741fe45a6edac6d8d81b39acb0351e1111454137b0c10e6646c98db31", @"/Views/_ViewImports.cshtml")]
    #nullable restore
    public class Views_Jogos_Index : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<List<Projeto_Integrador.Models.Jogo>>
    #nullable disable
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\n<h1>Jogos</h1>\r\n\r\n<table>\r\n    <tr>\r\n        <th>ID</th>\r\n        <th>Nome</th>\r\n        <th>Descrição</th>\r\n        <th>Imagem</th>\r\n        <th>Ações</th>\r\n    </tr>\r\n");
#nullable restore
#line 13 "C:\Users\cauag\Documents\SENAC\Modulo 1\Projeto Integrador\Views\Jogos\Index.cshtml"
     foreach (var jogo in Model)
    {

#line default
#line hidden
#nullable disable
            WriteLiteral("        <tr>\r\n            <td>");
#nullable restore
#line 16 "C:\Users\cauag\Documents\SENAC\Modulo 1\Projeto Integrador\Views\Jogos\Index.cshtml"
           Write(jogo.Id);

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n            <td>");
#nullable restore
#line 17 "C:\Users\cauag\Documents\SENAC\Modulo 1\Projeto Integrador\Views\Jogos\Index.cshtml"
           Write(jogo.Nome);

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n            <td>");
#nullable restore
#line 18 "C:\Users\cauag\Documents\SENAC\Modulo 1\Projeto Integrador\Views\Jogos\Index.cshtml"
           Write(jogo.Descricao);

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n            <td><img src=\"https://jogandoagora.com.br/wp-content/uploads/2015/02/Project-Zomboid-capa1-808x454.png\"");
            BeginWriteAttribute("alt", " alt=\"", 488, "\"", 504, 1);
#nullable restore
#line 19 "C:\Users\cauag\Documents\SENAC\Modulo 1\Projeto Integrador\Views\Jogos\Index.cshtml"
WriteAttributeValue("", 494, jogo.Nome, 494, 10, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(" style=\"width: 100px;\"></td>\r\n            <td>\r\n                <a");
            BeginWriteAttribute("href", " href=\"", 571, "\"", 628, 1);
#nullable restore
#line 21 "C:\Users\cauag\Documents\SENAC\Modulo 1\Projeto Integrador\Views\Jogos\Index.cshtml"
WriteAttributeValue("", 578, Url.Action("Edit", "Jogos", new { id = jogo.Id }), 578, 50, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(">Editar</a> |\r\n                <a");
            BeginWriteAttribute("href", " href=\"", 662, "\"", 721, 1);
#nullable restore
#line 22 "C:\Users\cauag\Documents\SENAC\Modulo 1\Projeto Integrador\Views\Jogos\Index.cshtml"
WriteAttributeValue("", 669, Url.Action("Delete", "Jogos", new { id = jogo.Id }), 669, 52, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(">Excluir</a>\r\n            </td>\r\n        </tr>\r\n");
#nullable restore
#line 25 "C:\Users\cauag\Documents\SENAC\Modulo 1\Projeto Integrador\Views\Jogos\Index.cshtml"
    }

#line default
#line hidden
#nullable disable
            WriteLiteral("</table>\r\n\r\n<a");
            BeginWriteAttribute("href", " href=\"", 791, "\"", 828, 1);
#nullable restore
#line 28 "C:\Users\cauag\Documents\SENAC\Modulo 1\Projeto Integrador\Views\Jogos\Index.cshtml"
WriteAttributeValue("", 798, Url.Action("Create", "Jogos"), 798, 30, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(">Adicionar novo jogo</a>\r\n");
        }
        #pragma warning restore 1998
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<List<Projeto_Integrador.Models.Jogo>> Html { get; private set; } = default!;
        #nullable disable
    }
}
#pragma warning restore 1591
